export const homeObjOne = {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topline: 'Easy Navigation',
    headline: 'Easy Campus Navigation to prevent getting lost and late',
    description: 'Searching for some destination within the campus? Try our Campus Navigation App and never lose your way again.',
    buttonLabel: 'Get Started',
    imgStart: true,
    img: require('../image/img-1.png'),
    alt: 'Car',
    dark: true,
    primary: true,
    darkText: false,
};
export const homeObjTwo = {
    id: 'discover',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topline: 'Unlimited access',
    headline: 'Unlimited transactions with zero fees',
    description: 'Get access to our exclusive app that allows you to send unlimited transactions without getting charged any fees',
    buttonLabel: 'Learn More',
    imgStart: true,
    img: require('../image/img-1.png'),
    alt: 'Car',
    dark: false,
    primary: false,
    darkText: true,
};
export const homeObjThree = {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topline: 'Premium Bank',
    headline: 'Unlimited transactions with zero fees',
    description: 'Get access to our exclusive app that allows you to send unlimited transactions without getting charged any fees',
    buttonLabel: 'Get Started',
    imgStart: true,
    img: require('../image/img-1.png'),
    alt: 'Car',
    dark: true,
    primary: true,
    darkText: false,
};
